# MLOps Pipeline Configuration
# Sheikh-Freemium Visual CoT

pipeline:
  name: visual-cot-training
  version: "1.0.0"
  
triggers:
  # Data changes trigger training
  data_update:
    paths:
      - "dataset/samples/**"
      - "dataset/schemas/**"
    action: validate_and_queue
  
  # Prompt changes trigger retraining
  prompt_update:
    paths:
      - "prompts/**"
    action: retrain
  
  # Training config changes
  training_update:
    paths:
      - "training/**"
    action: full_train
  
  # Scheduled continuous learning
  schedule:
    cron: "0 0 * * 0"  # Weekly
    action: continuous_learn

stages:
  # Stage 1: Data Validation
  validate:
    name: "Validate Data & Prompts"
    steps:
      - validate_schema
      - check_data_quality
      - validate_prompts
    on_failure: notify
  
  # Stage 2: Training
  train:
    name: "Fine-tune Model"
    depends_on: validate
    config:
      base_model: "multimodal-reasoning-lab/Anole-Zebra-CoT"
      learning_rate: 2e-5
      batch_size: 8
      epochs: 3
      gradient_accumulation: 4
    resources:
      gpu: "A100"
      memory: "80GB"
    outputs:
      - weights
      - metrics
      - logs
  
  # Stage 3: Validation
  validate_weights:
    name: "Validate Model Weights"
    depends_on: train
    checks:
      - accuracy_threshold: 0.15  # Must exceed 15%
      - regression_check: true
      - benchmark_suite:
          - visual_reasoning
          - scientific
          - logic_games
    on_failure: rollback
  
  # Stage 4: Release
  release:
    name: "Release Model"
    depends_on: validate_weights
    targets:
      - huggingface:
          repo: "shk-bd/Sheikh-Freemium"
          type: model
      - github:
          release: true
          tag_format: "v{version}"
    versioning:
      strategy: semantic
      auto_increment: patch
  
  # Stage 5: Continuous Learning
  continuous_learn:
    name: "Update for Continuous Learning"
    depends_on: release
    actions:
      - update_base_model
      - archive_previous_version
      - prepare_next_iteration

notifications:
  slack:
    webhook: "${{ secrets.SLACK_WEBHOOK }}"
    events: [success, failure]
  email:
    recipients: ["team@example.com"]
    events: [failure]

artifacts:
  storage:
    provider: huggingface
    retention_days: 90
  checkpoints:
    save_frequency: 500  # steps
    keep_last: 3
